### ISSUE TITLE
ARM64 doesn't need `$INODE64` suffix?

### ISSUE THREAD

**Issue by elliottkember** [al45tair/mac_alias#10]
Hello!

I'm using this package as part of `electron-builder` and I've hit a snag using it on an M1 mac.

This is the traceback I get:

      ⨯ Exit code: 1. Command failed: /usr/bin/python /Users/elliott/appname/.yalc/dmg-builder/vendor/dmgbuild/core.py
    Traceback (most recent call last):
      File "/Users/elliott/appname/.yalc/dmg-builder/vendor/dmgbuild/core.py", line 25, in <module>
        from mac_alias import *
      File "/Users/elliott/appname/.yalc/dmg-builder/vendor/mac_alias/__init__.py", line 1, in <module>
        from .alias import *
      File "/Users/elliott/appname/.yalc/dmg-builder/vendor/mac_alias/alias.py", line 16, in <module>
        from . import osx
      File "/Users/elliott/appname/.yalc/dmg-builder/vendor/mac_alias/osx.py", line 424, in <module>
        _statfs = libc['statfs$INODE64']
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 384, in __getitem__
        func = self._FuncPtr((name_or_ordinal, self))
    AttributeError: dlsym(0x100ed1690, statfs$INODE64): symbol not found

However, running the command with the `arch -x64_64` prefix made the problem disappear.

I've found [this page](https://assert.cc/posts/darwin_use_64_bit_inode_vs_ctypes/) when looking for the $INODE64 suffix.  I tested this out with Rosetta (`arch -x86_64` prefix), and sure enough `libc['statfs$INODE64']` is available under Rosetta, but not under native Python.

I'm wondering whether the approach of 

    try:
        getmntinfo = libc["getmntinfo$INODE64"]
    except (KeyError, AttributeError):
        # HOPE THIS DOESN'T RETURN A DIFFERENT STATFS STRUCT.
        getmntinfo = libc["getmntinfo"]

would be a good addition?

Also linking [this issue](https://github.com/electron-userland/electron-builder/pull/5426#issuecomment-739565640) where I brought this up in `electron-builder`.

**Comment by al45tair** [comment]
Very likely that's the right fix, yes. I have an M1 Mac mini turning up soon so I should be able to check this myself (I'll make sure the statfs struct looks the same).

The `$INODE64` suffix (and a few other similar ones) are basically a backwards compatibility measure on the Intel Mac platform, to make it easy for code compiled on an earlier SDK (which might not have had 64-bit inode numbers) to just work on a newer machine. It isn't particularly surprising that it doesn't exist on the ARM Macs because they didn't ever have 32-bit inode numbers, so why have the decorated name? :-)

**Comment by elliottkember** [comment]
Here's an easy way to test it:

    from __future__ import unicode_literals
    from ctypes import *
    import struct
    import os
    import datetime
    import uuid
    libc = cdll.LoadLibrary('/usr/lib/libc.dylib')
    print 'statfs:'
    _statfs = libc['statfs']
    print 'ok!'
    print 'statfs$INODE64:'
    _statfs = libc['statfs$INODE64']
    print 'ok!'

The output on my M1 MBP:

    MacBook-Pro ~/Desktop arch -x86_64 python test.py
    statfs:
    ok!
    statfs$INODE64:
    ok!
    
    MacBook-Pro ~/Desktop python test.py
    statfs:
    ok!
    statfs$INODE64:
    Traceback (most recent call last):
      File "/Users/elliott/Desktop/test.py", line 12, in <module>
        _statfs = libc['statfs$INODE64']
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 384, in __getitem__
        func = self._FuncPtr((name_or_ordinal, self))
    AttributeError: dlsym(0x1006a5690, statfs$INODE64): symbol not found

**Comment by al45tair** [comment]
This is now fixed and a new version of `mac_alias` has been released (version 2.2.0).

**Comment by rggarix** [comment]
I tried to Re-install the dmg-builder module and it worked.
link:- https://www.npmjs.com/package/dmg-builder
